### ISSUE TITLE
Did you port netfilter?

### ISSUE THREAD

**Issue by alexsalig** [vadimsu/ipaugenblick#3]
Did you port netfilter completely? if no, which parts are ported? which rules can be defined?

**Comment by vadimsu** [comment]
no, I didn't

**Comment by alexsalig** [comment]
Thanks for your response. 
I want to port the netfilter, as a start I want to port as less as possible to define simplest rules via iptables (e.g. droping packets from a specified IP address). With which files I should start? could you provide some guide lines for me?

**Comment by vadimsu** [comment]
1. copy net/ipv4/netfilter folder from original 3.14 kernel under net/ipv4. According to your description, it looks like you need to port iptable filter table (iptable_filter.c), ip_tables.c , REJECT target (ipt_REJECT.c) 
2. copy net/netfilter/x_tables.c from original 3.14 kernel under corresponding location and port it
3. Call init functions for added modules in appropriated places
This is to start. It is a time-consuming project, to port iptables.

**Comment by alexsalig** [comment]
Thank you so much!
